name = "animal-football"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[routes]]
pattern = "football.allrich.ai"
custom_domain = true
